feat: add migration mode option to Install-EsxiCertificate
vmware/powershell-module-for-vmware-cloud-foundation-certificate-management pull request #101
Opened 2024-01-05 20:22 UTC by garlicNova

cmdlet Install-EsxiCertificate add "EnsureAccessibility" options add cmdlet "Get-EsxiHostVsanMaintenanceModePrecheck"

cmdlet Install-EsxiCertificate add "EnsureAccessibility" options
add cmdlet "Get-EsxiHostVsanMaintenanceModePrecheck"

Signed-off-by: Kevin Teng <kevin.teng@broadcom.com> 

### Type

- [x] Bugfix
- [x] Enhancement or Feature
- [ ] Code Style or Formatting
- [x] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [x] Yes, there are breaking changes.
- [ ] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [x] Documentation has been added or updated.

### Issue References

Closes #32 
Closes #100

### Additional Information

2024-01-08 20:48 UTC, bhumitra commented on docs/documentation/functions/Get-EsxiHostVsanMaintenanceModePrecheck.md
> +Get-EsxiLockdownMode [-server] <String> [-user] <String> [-pass] <String> [-domain] <String> [-cluster] <String> [[-esxiFqdn] <String>] [<CommonParameters>]
Update the example. It should be Get-EsxiHostVsanMaintenanceModePrecheck

2024-01-08 20:58 UTC, bhumitra commented
@garlicNova The `Install-VCFCertificate` cmdlet is the one which is exposed to the user. 
Hence for the user to use the changes made for `Install-EsxiCertificate` for ensureAccesibility, we must allow configuration of the parameters from Install-VCFCertificate. Could you please make that change.

2024-01-12 16:12 UTC, tenthirtyam requested changes
@garlicNova - can you address Bhumitra's comments today?

2024-01-12 20:51 UTC, tenthirtyam commented on VMware.CloudFoundation.CertificateManagement.psd1
> +    ModuleVersion = '1.6.0.1000'
Fixed the version.

2024-01-12 20:51 UTC, tenthirtyam commented on CHANGELOG.md
> +
Updated.

2024-01-12 20:51 UTC, tenthirtyam commented on VMware.CloudFoundation.CertificateManagement.psm1
> +        The cmdlet will halt the script if the pre check fails.
Updated.

2024-01-12 20:52 UTC, tenthirtyam commented on docs/documentation/functions/Get-EsxiHostVsanMaintenanceModePrecheck.md
> +Checks for any issues when the ESXi H=host enters a particular vSAN maintenance mode.
Updated.

2024-01-12 20:57 UTC, tenthirtyam approved these changes
Made some updates to quicken the review.

Now LGTM!

2024-01-12 20:57 UTC, tenthirtyam commented on VMware.CloudFoundation.CertificateManagement.psm1
> +        will enter maintenance mode with Migrate Power off VMs option disabled and vSAN data migration Mode set to EnsureAccessibility.
Updated.

2024-01-12 20:57 UTC, tenthirtyam commented on VMware.CloudFoundation.CertificateManagement.psm1
> +        will enter maintenance mode with Migrate Power off VMs option enabled and vSAN data migration Mode set to EnsureAccessibility.
Updated.

2024-01-12 20:57 UTC, tenthirtyam commented on docs/documentation/functions/Install-VCFCertificate.md
> +This example will install the certificate to the ESXi host sfo01-m01-esx01.sfo.rainpole.io in domain sfo-m01 from the provided path. The ESXi host will enter maintenance mode with Migrate Power off V
Updated.

2024-01-12 20:57 UTC, tenthirtyam commented on docs/documentation/functions/Install-VCFCertificate.md
> +This example will install certificates for each ESXi host in cluster sfo-m01-cl01 in workload domain sfo-m01 from the provided path. The ESXi host will enter maintenance mode with Migrate Power off V
Updated.

2024-01-12 20:59 UTC, tenthirtyam commented
Passing to @bhumitra for next review.

2024-01-12 22:56 UTC, bhumitra commented on docs/documentation/functions/Get-EsxiHostVsanMaintenanceModePrecheck.md
> +The passwordto authenticate to the SDDC Manager instance.
```suggestion
The password to authenticate to the SDDC Manager instance.
```

2024-01-12 23:08 UTC, bhumitra submitted a review, later dismissed
I am good with the changes now. Made a minor fix. 🚀  LGTM

2024-01-12 23:32 UTC, tenthirtyam commented
Thanks! I'll rebase and merge.

2024-01-12 23:43 UTC, merged