Changed for oct release
vmware/powershell-module-for-vmware-cloud-foundation-certificate-management pull request #74
Opened 2023-09-29 18:05 UTC by bhumitra

### Summary

- **Breaking Change**: Renamed `Set-SddcCertificateAuthority` to `Set-VCFCertificateAuthority`
- **Breaking Change**: Renamed `Request-SddcCertificate` to `Request-VCFSignedCertificate` 
- Updated docs as per above changes. 

### Type

- [ ] Bugfix
- [x] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [x] Yes, there are breaking changes.
- [ ] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [x] Documentation has been added or updated.

### Issue References

Closes #73 
### Additional Information

2023-09-29 22:35 UTC, tenthirtyam requested changes
Minor changes.

2023-09-29 22:35 UTC, tenthirtyam commented on CHANGELOG.md
> +- **Breaking Change**: Renamed `Set-SddcCertificateAuthority` to `Set-VCFCertificateAuthority`
```suggestion
- **Breaking Change**: Renamed `Set-SddcCertificateAuthority` to `Set-VCFCertificateAuthority`. [GH-74](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/pull/74)
```

2023-09-29 22:35 UTC, tenthirtyam commented on CHANGELOG.md
> +- **Breaking Change**: Renamed `Request-SddcCertificate` to `Request-VCFSignedCertificate`
```suggestion
- **Breaking Change**: Renamed `Request-SddcCertificate` to `Request-VCFSignedCertificate`. [GH-74](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/pull/74)
```

2023-09-29 22:35 UTC, tenthirtyam commented on VMware.CloudFoundation.CertificateManagement.psm1
> + # Copyright 2023 VMware, Inc.
```suggestion
# Copyright 2023 VMware, Inc.
```

2023-09-29 22:35 UTC, tenthirtyam commented on VMware.CloudFoundation.CertificateManagement.psm1
> +        The type of Certificate Authority to be used for signing certificates - Microsoft or OpenSSL
```suggestion
        The type of Certificate Authority to be used for signing certificates. One of: Microsoft, OpenSSL.
```

2023-09-30 02:36 UTC, bhumitra commented
Applied suggested changes.

2023-09-30 03:04 UTC, tenthirtyam approved these changes
LGTM

2023-09-30 03:06 UTC, merged